# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

pow_list <- c(0.8, 0.85, 0.9, "a")

test_that("gen_pow_curve works", {
  expect_error(gen_pow_curve(seq = pow_list,
                        sen_spe = 0.9,
                        alpha = 0.05,
                        margin = 0.05,
                        prevalence = 0.4,
                        prevalence_power = 0.8 ,
                        performance_characteristic = "sen")) 
})

test_that("n_por_prop works", {
   expect_equal(n_pop_prop(alpha = 0.05, p =  0.5, margin = 0.1), 97)
    expect_equal(n_pop_prop(alpha = 0.05, p =  0.5, margin = 0.1, N=100), 50)
})

# Unpaired design - the number of clusters required for each treatment group
# incidence of a disease in control group: 0.0148
# incidence in intervention group: 0.0104
# desired power: 0.8
# significance : 0.05
# people per cluster : 424
# variation in clusters: 0.29
test_that("cluster_random_sample_size works", {
  expect_equal(cluster_random_sample_size(alpha = 0.05, power =0.8, coef_var = 0.29, A =1, pi =0.0104, pc = 0.0148, CS = 424), 36)
})

# Calculates effective sample size
# number of participants in a cluster: 32
# number of clusters: 4
# intracluster correlation coefficient: 0.017

test_that("effective_sample_size works", {
  expect_equal(effective_sample_size(m = 32, k = 4, ICC = 0.017), 84)
})

