# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

test_that("sample_size_calculation works", {
  expect_equal(sample_size_calculation(sen_spe= 0.8, alpha=0.05, power=0.8, margin=0.05, prevalence = NULL, prevalence_power = NULL, performance_characteristic = "sen"), 503)
})

test_that("n_tot_calculation works", {
  expect_equal(n_tot_calculation(sample_size=503, prevalence = 0.1, prevalence_power = 0.9 ), 5311)
})

test_that("margin_calc works", {
  expect_equal(margin_calc(alpha=0.05, power=0.8, sen_spe=0.8, sample_size=502), 0.05)
})

test_that("power_calc works", {
  expect_equal(power_calc(alpha=0.05, margin=0.05, sen_spe=0.8, sample_size=502), 0.8)
})
