# Generated by fusen: do not edit by hand

#' compare_proportions_cross
#' 
#' Sample size calculation to compare proportions in a cross-over design
#' 
#' @param alpha significance level, default 5%
#' @param power desired power, default 80%
#' @param p_diff difference between the proportions of incidence
#' @param var variance of the d
#' @references Chow, S. C., Shao, J., Wang, H., & Lokhnygina, Y. (2017). Sample size calculations in clinical research. chapman and hall/CRC.

#' @return
#' 
#' @export
#' @examples
#' # Difference between the two proportions are predicted to be 10%
#' compare_proportions_cross(alpha = 0.05, power = 0.8, p_diff = 0.1, var = 0.5)
compare_proportions_cross <- function(alpha = 0.05, power = 0.8, p_diff, var = 0.5){
  alpha_val         <- 1-alpha/2
  zz <- (qnorm(alpha_val) + qnorm(power))^2
  ss <- var^2
  denom <- (p_diff^2)*2
  sample_size <- (zz*ss)/denom
  return(ceiling(sample_size))
  
     
}
