# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' Sample Size for detecting a difference between two tests 
#' 
#' Sample size calculation when comparing sensitivities/specifies in paired groups by McNemar, according to Beam, 1992, Table 4. Three sample sizes are given taking into account the minimum (N_min) and the maximum (N_max) bounds on the probability of disagreement, and their mean (N_mean). The original formula is for equivalence testing. The hypothesis of detecting a specified difference (delta_m) was done as in Blackwleder 1982 by introducing the specified difference to the denominator.
#' 
#' 
#' @param theta_s numeric value between 0 and 1. performance estimate of standard test
#' @param theta_e numeric value between 0 and 1. performance estimate of experimental test
#' @param delta_m numeric value. maximal acceptable difference to conclude non-inferiority.
#' @param alpha numeric value. Significance level
#' @param beta numeric value. beta = 1 - Power 

#' 
#' @importFrom stats qnorm
#'
#' @return numeric values giving the min-mean-max number of samples required
#' @references Blackwelder WC. "Proving the Null Hypothesis" in Clinical Trials. Control. Clin. Trials 1982; 3:345-353.
#' @references Beam, C. A. (1992). Strategies for improving power in diagnostic radiology research. American Journal of Roentgenology 159, 631-637.
#' @export
#' 
#' @examples
#' \dontrun{
#' ss_compare_sen_spe(theta_s = 0.45, theta_e = 0.43, delta_m = 0.07, beta = 0.8)
#' ss_compare_sen_spe(theta_s = 0.45, theta_e = 0.43, delta_m = 0, beta = 0.8)
#' }
  ss_compare_sen_spe  <- function(theta_s, theta_e, delta_m, alpha = 0.05, beta = 0.8){
    phi_min <- theta_s - theta_e
  phi_max <- theta_s * (1 - theta_e) + theta_e * (1 - theta_s)
  phi_vec <- c(phi_min, phi_max)


  ss.range <- sapply(phi_vec, function(phi){
    (qnorm(1 - alpha) * sqrt(phi) + qnorm(beta) * sqrt(phi-phi_min^2))^2 / (phi_min-delta_m)^2
  })
  
  Ns <- ceiling(c(N_min = ss.range[1], N_mean = mean(ss.range[1:2]), N_max = ss.range[2]))

  return(Ns)


}
