# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' Sample Size non-inferiority method 2 
#' 
#' Gives a sample size range for a diagnostic accuracy trial with non-inferiority hypothesis, based on estimated accuracy for each test and a minimum non-acceptable difference (Eq. 6.24 from Zhou et al. 2011)  Variance is calculated using the Eq.6.15 from Zhou et al., with a
#' 
#' @param theta_s numeric value between 0 and 1. performance estimate of standard test
#' @param theta_e numeric value between 0 and 1. performance estimate of experimental test
#' @param delta_m numeric value. maximal acceptable difference to conclude non-inferiority.
#' @param alpha numeric value. Significance level
#' @param beta numeric value. beta = 1 - Power 
#' @param p11 numeric value. Probability that standard test is positive when experimental test is positive, when estimation is possible from preliminary data
#' 
#' @importFrom stats qnorm
#'
#' @return numeric value giving the number of samples required
#' @export
#' @examples
#' \dontrun{
#' ss_non_inf_2(theta_s = 0.45, theta_e = 0.43, delta_m = 0.07, beta = 0.8)
#' ss_non_inf_2(theta_s = 0.45, theta_e = 0.43, delta_m = 0.07, beta = 0.8, p11 = 0.5)
#' }
#'
#' sample_size_non_inferiority(se1 = 0.9, se2 = 0.88, r = 0.5, min_dif=0.05, alpha=0.05, power=0.8)
ss_non_inf_2 <- function(theta_s, theta_e, delta_m, alpha = 0.05, beta = 0.8, p11 = NULL){
  phi_min <- theta_s - theta_e
  phi_max <- theta_s * (1 - theta_e) + theta_e * (1 - theta_s)
  phi_vec <- c(phi_min, phi_max)
  
  if(!is.null(p11)){
    phi_est <- theta_s + theta_e - 2 * theta_e * p11
    phi_vec <- c(phi_vec, phi_est)
  }
  
  ss.range <- sapply(phi_vec, function(phi){
    ((qnorm(1 - alpha/2) + qnorm(beta))^2 * (phi - phi_min ^ 2)) / ((phi_min - delta_m)^2)
  })
  
  Ns <- ceiling(c(N_min = ss.range[1], N_mean = mean(ss.range[1:2]), N_max = ss.range[2]))
  if(!is.null(p11)){
    Ns <- c(Ns, N_est = ceiling(ss.range[3]))
  }
  return(Ns)

}
